// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nytzitewhdpimmyxouys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dHppdGV3aGRwaW1teXhvdXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Nzk3ODIsImV4cCI6MjA2MTI1NTc4Mn0.BGOnAbxZ0RdyOP1sGLFmjarxlKj8Ox0vfQPM5LuvLM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);